<a href="https://colab.research.google.com/github/code-1-mukul/Deep-Learning-Lab/blob/main/DL_LAB_1_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Creating Tensors


Pytorch

In [1]:
import torch

# 1D Tensor (Vector)
t1 = torch.tensor([1, 2, 3])

# 2D Tensor (Matrix)
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])

# 3D Tensor
t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])


Numpy

In [2]:
import numpy as np

# 1D array
a1 = np.array([1, 2, 3])

# 2D array
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# 3D array
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])


### Basics Element Wise Operation

Pytorch

In [3]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

x + y      # addition
x - y      # subtraction
x * y      # multiplication
x / y      # division


tensor([0.2500, 0.4000, 0.5000])

Numpy

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y
x - y
x * y
x / y


array([0.25, 0.4 , 0.5 ])

###Dot Product and Matrix Multiplication

####Dot Product (1D)

Pytorch

In [5]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

torch.dot(a, b)   # Output: scalar


tensor(32)

Numpy

In [6]:
np.dot(a, b)


/tmp/ipython-input-4196905992.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np.dot(a, b)


np.int64(32)

#####Matrix Multiplication (2D)

Pytorch

In [7]:
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

A @ B
torch.matmul(A, B)


tensor([[19, 22],
        [43, 50]])

Numpy

In [8]:
A @ B
np.matmul(A, B)


/tmp/ipython-input-2502605517.py:2: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  np.matmul(A, B)


tensor([[19, 22],
        [43, 50]])

####Indexing and Slicing

Basic Indexing

In [9]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

t[0, 1]     # 20
t[:, 1]     # Column
t[1, :]     # Row


tensor([40, 50, 60])

Boolean Masking

In [10]:
x = torch.tensor([1, 2, 3, 4, 5])
mask = x > 3

x[mask]     # tensor([4, 5])


tensor([4, 5])

NumPy:

In [11]:
x[x > 3]


tensor([4, 5])

Extracting Sub-tensors

In [12]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub = t[0:2, 1:3]


####Reshaping Operations

PyTorch

In [13]:
x = torch.arange(6)

x.view(2, 3)      # Only works if memory is contiguous
x.reshape(2, 3)   # Safer, works even if not contiguous


tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
x = torch.tensor([1, 2, 3])

x_unsq = x.unsqueeze(0)   # Shape: (1, 3)
x_unsq = x.unsqueeze(1)   # Shape: (3, 1)

x_sq = x_unsq.squeeze()   # Removes dimensions of size 1


Numpy

In [15]:
x = np.array([1, 2, 3, 4, 5, 6])
x.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

####Broadcasting

Pytorch

In [16]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([10, 20, 30])

A + b


tensor([[11, 22, 33],
        [14, 25, 36]])

Numpy

In [17]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

A + b


array([[11, 22, 33],
       [14, 25, 36]])

####In-place vs Out-of-place Operations

Out-of-place

In [18]:
x = torch.tensor([1, 2, 3])
y = x + 5

print(x)  # unchanged


tensor([1, 2, 3])


In-place

In [19]:
x = torch.tensor([1, 2, 3])
x.add_(5)

print(x)  # modified


tensor([6, 7, 8])
